# file: site.yml
- include: tasks/git.yml
- include: tasks/dir_struct.yml
- include: tasks/miniconda.yml
# - include: tasks/spf13_vim.yml
# - include: tasks/ide_pycharm.yml
# - include: tasks/ide_pydev.yml

