---
# file: tasks/ide_pycharm.yml
- hosts: localhost
  sudo: True

  tasks:
      - name: Install pycharm and its java dependencies
        command: ../scripts/install_pycharm &> pycharm_install.log

