---
# file:  tasks/prerequisites.yml

- hosts: localhost
  sudo: True

  tasks:
    # -------------------------------------------------------------------------
    # Update all packages to newest in distribution: s.b. done first
    # -------------------------------------------------------------------------
    - name: update all packages to latest version
      apt:
        upgrade=dist

    # -------------------------------------------------------------------------
    # Install Oracle Java 8 and make default java on the system
    # -------------------------------------------------------------------------
    - name: removed openjdk
      apt:
          name:  openjdk*
          state:  absent

    - name: update ppa with webupd8team
      # this creates duplicates so may need to look at cleaning up later
      command:  sudo add-apt-repository ppa:webupd8team/java

    - name: install oracle 8
      apt:
          name:  oracle-java8-installer
          update_cache: yes  # equiv of apt-get update
          state:  present

    # -------------------------------------------------------------------------
    # Update git to insure it is installed and at latest version in repo
    # -------------------------------------------------------------------------
    - name: ensure git is at latest version
      apt:
          pkg: git
          state: latest

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Get runcons for default bashrc
    # and condarc from git repo
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: clone the runcons project for rc files
      git: repo=https://github.com/lowcloudnine/runcons.git
           dest=../runcons
           refspec=+refs/pull/*:refs/heads/*

    - name: change the owner on runcons
      file: path=../runcons
            state=directory
            recurse=yes
            owner={{ ansible_ssh_user }}
            mode=0755

    # -----------------------------------------------------------------------
    # Create the required directory structure
    # -----------------------------------------------------------------------
    - name: create python development directory under opt
      file: path=/opt/pytools state=directory
            owner={{ ansible_ssh_user }}
            mode=0755

    - name: create a envs directory under /opt/py_devtools
      file: path=/opt/pytools/envs state=directory
            owner={{ ansible_ssh_user }}
            mode=0755

    - name: create a projects directory in /opt for the users projects
      file: path=/opt/projects state=directory
            owner={{ ansible_ssh_user }}
            mode=0755